#!/usr/bin/env python3
"""
Identify which USB serial port belongs to which arm and create persistent udev rules.

Scans /dev/ttyUSB* ports, reads Dynamixel motor model numbers to distinguish
leader (all XL430) from follower (has XM430 on load-bearing joints). Creates
/dev/ttyDXL* symlinks via udev rules that survive reboots.
"""

import glob
import os
import subprocess
import sys
import time

from dynamixel_sdk import PortHandler, PacketHandler, COMM_SUCCESS

PROTOCOL_VERSION = 2.0
BAUDRATE = 1000000

MODEL_XL430_W250 = 1060
MODEL_XM430_W210 = 1030
MODEL_NAMES = {
    MODEL_XL430_W250: 'XL430-W250',
    MODEL_XM430_W210: 'XM430-W210',
    1000: 'X430-350 (model 1000)',
}

MOTOR_IDS = [1, 2, 3, 4, 5]
ADDR_MODEL_NUMBER = 0

UDEV_RULES_FILE = '/etc/udev/rules.d/99-dynamixel.rules'
UDEV_LINK_PRIORITY = 100

DXL_ASSIGNMENTS = {
    'left':  {'leader': 'ttyDXL0', 'follower': 'ttyDXL1'},
    'right': {'leader': 'ttyDXL2', 'follower': 'ttyDXL3'},
}


def set_usb_latency(port, latency_ms=1):
    """Set USB latency timer (16ms default is too slow for Dynamixel comms)."""
    device = os.path.basename(port)
    latency_file = f'/sys/bus/usb-serial/devices/{device}/latency_timer'
    try:
        with open(latency_file, 'w') as f:
            f.write(str(latency_ms))
    except (PermissionError, FileNotFoundError):
        pass


def get_usb_serial(port):
    try:
        output = subprocess.check_output(
            ['udevadm', 'info', '-a', '-n', port],
            text=True
        )
        for line in output.splitlines():
            line = line.strip()
            if line.startswith('ATTRS{serial}==') and '0000:' not in line:
                return line.split('"')[1]
    except Exception:
        pass
    return None


def scan_port(port):
    set_usb_latency(port)

    port_handler = PortHandler(port)
    packet_handler = PacketHandler(PROTOCOL_VERSION)

    if not port_handler.openPort():
        return {}
    if not port_handler.setBaudRate(BAUDRATE):
        port_handler.closePort()
        return {}

    motors = {}
    for motor_id in MOTOR_IDS:
        model, result, _ = packet_handler.read2ByteTxRx(
            port_handler, motor_id, ADDR_MODEL_NUMBER
        )
        if result == COMM_SUCCESS:
            motors[motor_id] = model

    port_handler.closePort()
    return motors


def identify_arm(motors):
    if not motors:
        return 'unknown'

    if all(m == MODEL_XL430_W250 for m in motors.values()):
        return 'leader'

    # Follower has non-XL motors on load-bearing joints (some report model 1000)
    if any(m != MODEL_XL430_W250 for m in motors.values()):
        return 'follower'

    return 'unknown'


def load_existing_rules():
    existing = {}
    if not os.path.exists(UDEV_RULES_FILE):
        return existing

    try:
        with open(UDEV_RULES_FILE, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                serial = symlink = None
                for part in line.split(','):
                    part = part.strip()
                    if 'ATTRS{serial}' in part:
                        serial = part.split('"')[1]
                    if 'SYMLINK' in part:
                        symlink = part.split('"')[1]
                if serial and symlink:
                    existing[serial] = symlink
    except PermissionError:
        try:
            output = subprocess.check_output(
                ['sudo', 'cat', UDEV_RULES_FILE], text=True
            )
            for line in output.splitlines():
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                serial = symlink = None
                for part in line.split(','):
                    part = part.strip()
                    if 'ATTRS{serial}' in part:
                        serial = part.split('"')[1]
                    if 'SYMLINK' in part:
                        symlink = part.split('"')[1]
                if serial and symlink:
                    existing[serial] = symlink
        except Exception:
            pass

    return existing


def build_rules_content(rules):
    lines = [
        '# Dynamixel USB adapters - auto-generated by identify_arms.py',
        '# Maps USB serial numbers to /dev/ttyDXL* symlinks',
        '#',
    ]
    for serial, (symlink, comment) in sorted(rules.items(), key=lambda x: x[1][0]):
        lines.append(f'# {comment}')
        lines.append(
            f'SUBSYSTEM=="tty", ATTRS{{serial}}=="{serial}", '
            f'SYMLINK+="{symlink}", ATTR{{latency_timer}}="1", '
            f'OPTIONS+="link_priority={UDEV_LINK_PRIORITY}"'
        )
        lines.append('')

    return '\n'.join(lines) + '\n'


def sudo_write_file(path, content):
    proc = subprocess.run(
        ['sudo', 'tee', path],
        input=content, text=True,
        stdout=subprocess.DEVNULL
    )
    return proc.returncode == 0


def refresh_udev_symlinks():
    for i in range(4):
        link = f'/dev/ttyDXL{i}'
        if os.path.islink(link):
            subprocess.run(['sudo', 'rm', link], check=False)

    subprocess.run(['sudo', 'udevadm', 'control', '--reload-rules'], check=True)
    subprocess.run(['sudo', 'udevadm', 'trigger'], check=True)
    time.sleep(1)


def rewrite_existing_rules(existing_rules, dry_run=False):
    all_rules = {
        serial: (symlink, '(preserved mapping)')
        for serial, symlink in existing_rules.items()
    }
    content = build_rules_content(all_rules)

    if dry_run:
        print('--dry-run: would rewrite udev rules using current format.')
        return

    print(f'Rewriting {UDEV_RULES_FILE} with link_priority={UDEV_LINK_PRIORITY}...')
    if not sudo_write_file(UDEV_RULES_FILE, content):
        print('ERROR: Failed to rewrite udev rules.')
        sys.exit(1)


def main():
    dry_run = '--dry-run' in sys.argv
    refresh_only = '--refresh' in sys.argv

    existing_rules = load_existing_rules()
    known_serials = set(existing_rules.keys())

    if existing_rules:
        print('Existing udev rules:')
        for serial, symlink in sorted(existing_rules.items(), key=lambda x: x[1]):
            print(f'  {serial} -> /dev/{symlink}')
        print()

    if refresh_only:
        if not existing_rules:
            print('No existing udev rules found to refresh.')
            sys.exit(1)
        rewrite_existing_rules(existing_rules, dry_run=dry_run)
        if dry_run:
            print('--dry-run: would remove /dev/ttyDXL* symlinks and re-trigger udev rules.')
            return
        print('Refreshing /dev/ttyDXL* symlinks from existing udev rules...')
        refresh_udev_symlinks()
        for i in range(4):
            path = f'/dev/ttyDXL{i}'
            if os.path.exists(path):
                print(f'  {path} -> {os.path.realpath(path)}')
        print('Refresh complete.')
        return

    ports = sorted(glob.glob('/dev/ttyUSB*'))
    if not ports:
        print('No /dev/ttyUSB* ports found. Are the arms plugged in?')
        sys.exit(1)

    print(f'Found {len(ports)} USB serial port(s): {", ".join(ports)}\n')

    new_arms = {}
    for port in ports:
        serial = get_usb_serial(port)
        if not serial:
            print(f'{port}: could not read USB serial number, skipping')
            continue

        if serial in known_serials:
            symlink = existing_rules[serial]
            print(f'{port} (serial {serial}): already in udev rules as /dev/{symlink}')
            continue

        print(f'Scanning {port} (serial {serial})...')
        motors = scan_port(port)

        if not motors:
            print(f'  No motors found\n')
            continue

        arm_type = identify_arm(motors)

        for mid, model in sorted(motors.items()):
            name = MODEL_NAMES.get(model, f'Unknown({model})')
            print(f'  Motor {mid}: {name}')

        if arm_type == 'unknown':
            print(f'  -> UNKNOWN arm type, skipping\n')
            continue

        print(f'  -> {arm_type.upper()} arm\n')
        new_arms[port] = (arm_type, serial)

    if not new_arms:
        if existing_rules:
            print('No new arms to assign. Existing rules found.')
            rewrite_existing_rules(existing_rules, dry_run=dry_run)
            if dry_run:
                print('--dry-run: would refresh /dev/ttyDXL* symlinks from existing rules.')
            else:
                print('Refreshing /dev/ttyDXL* symlinks from existing rules...')
                refresh_udev_symlinks()
                for i in range(4):
                    path = f'/dev/ttyDXL{i}'
                    if os.path.exists(path):
                        print(f'  {path} -> {os.path.realpath(path)}')
        else:
            print('No arms detected on any port.')
        sys.exit(0)

    existing_symlinks = set(existing_rules.values())
    if 'ttyDXL0' not in existing_symlinks:
        pair = 'left'
    elif 'ttyDXL2' not in existing_symlinks:
        pair = 'right'
    else:
        print('All 4 DXL slots already have rules. To start over:')
        print(f'  sudo rm {UDEV_RULES_FILE}')
        print('  sudo udevadm control --reload-rules && sudo udevadm trigger')
        sys.exit(1)

    new_leaders = [(p, s) for p, (t, s) in new_arms.items() if t == 'leader']
    new_followers = [(p, s) for p, (t, s) in new_arms.items() if t == 'follower']

    if len(new_leaders) != 1 or len(new_followers) != 1:
        print(f'Expected exactly 1 leader and 1 follower, found '
              f'{len(new_leaders)} leader(s) and {len(new_followers)} follower(s).')
        print('Check connections and try again.')
        sys.exit(1)

    leader_port, leader_serial = new_leaders[0]
    follower_port, follower_serial = new_followers[0]
    leader_symlink = DXL_ASSIGNMENTS[pair]['leader']
    follower_symlink = DXL_ASSIGNMENTS[pair]['follower']

    print(f'Assigning {pair.upper()} pair:')
    print(f'  {leader_serial} ({leader_port}) -> /dev/{leader_symlink}  (leader_{pair})')
    print(f'  {follower_serial} ({follower_port}) -> /dev/{follower_symlink}  (follower_{pair})')

    if dry_run:
        print('\n--dry-run: no changes made.')
        return

    all_rules = {}
    for serial, symlink in existing_rules.items():
        all_rules[serial] = (symlink, '(previously assigned)')
    all_rules[leader_serial] = (leader_symlink, f'leader_{pair} - all XL430')
    all_rules[follower_serial] = (follower_symlink, f'follower_{pair} - has XM430')

    content = build_rules_content(all_rules)
    print(f'\nWriting udev rules to {UDEV_RULES_FILE} (sudo required)...')
    if not sudo_write_file(UDEV_RULES_FILE, content):
        print('ERROR: Failed to write udev rules.')
        sys.exit(1)

    refresh_udev_symlinks()
    print('Udev rules reloaded.\n')

    time.sleep(1)
    for symlink in [leader_symlink, follower_symlink]:
        path = f'/dev/{symlink}'
        if os.path.exists(path):
            target = os.path.realpath(path)
            print(f'  /dev/{symlink} -> {target}')
        else:
            print(f'  /dev/{symlink} NOT FOUND (may need replug)')

    print(f'\nDone! {pair.upper()} pair permanently assigned.')
    if pair == 'left':
        print('These will survive reboots and replugs.')
        print('Plug in the right pair and run this again.')
    else:
        print('All 4 arms permanently assigned. Ready to launch:')
        print('  ros2 launch teleop_controller dual_arm_bringup.launch.py')


if __name__ == '__main__':
    main()
